apiVersion: v1
kind: Service
metadata:
  name: texttospeech-service
spec:
  selector:
    app: texttospeech
  ports:
  - protocol: "TCP"
    port: 6002
    targetPort: 5002
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: texttospeech
spec:
  selector:
    matchLabels:
      app: texttospeech
  replicas: 2
  template:
    metadata:
      labels:
        app: texttospeech
    spec:
      containers:
      - name: texttospeech
        image: texttospeech:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002
