apiVersion: v1
kind: Service
metadata:
  name: object-detection-service
spec:
  selector:
    app: object-detection
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer


apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection
spec:
  selector:
    matchLabels:
      app: object-detection
  replicas: 2
  template:
    metadata:
      labels:
        app: object-detection
    spec:
      containers:
      - name: objectdetection
        image: objectdetection:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
