apiVersion: v1
kind: Service
metadata:
  name: summarization-service
spec:
  selector:
    app: summarization
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarization
spec:
  selector:
    matchLabels:
      app: summarization
  replicas: 2
  template:
    metadata:
      labels:
        app: summarization
    spec:
      containers:
      - name: summarization
        image: summarization:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
