apiVersion: v1
kind: Service
metadata:
  name: textgeneration-service
spec:
  selector:
    app: textgeneration
  ports:
  - protocol: "TCP"
    port: 6001
    targetPort: 5001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: textgeneration
spec:
  selector:
    matchLabels:
      app: textgeneration
  replicas: 2
  template:
    metadata:
      labels:
        app: textgeneration
    spec:
      containers:
      - name: textgeneration
        image: textgeneration:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
