apiVersion: v1
kind: Service
metadata:
  name: entity-extraction-service
spec:
  selector:
    app: entity-extraction
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer


apiVersion: apps/v1
kind: Deployment
metadata:
  name: entity-extraction
spec:
  selector:
    matchLabels:
      app: entity-extraction
  replicas: 2
  template:
    metadata:
      labels:
        app: entity-extraction
    spec:
      containers:
      - name: entityextraction
        image: entityextraction:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
