apiVersion: v1
kind: Service
metadata:
  name: questionanswering-service
spec:
  selector:
    app: questionanswering
  ports:
  - protocol: "TCP"
    port: 6001
    targetPort: 5001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: questionanswering
spec:
  selector:
    matchLabels:
      app: questionanswering
  replicas: 2
  template:
    metadata:
      labels:
        app: questionanswering
    spec:
      containers:
      - name: questionanswering
        image: questionanswering:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
