apiVersion: v1
kind: Service
metadata:
  name: face-detection-service
spec:
  selector:
    app: face-detection
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer


apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-detection
spec:
  selector:
    matchLabels:
      app: face-detection
  replicas: 2
  template:
    metadata:
      labels:
        app: face-detection
    spec:
      containers:
      - name: facedetection
        image: facedetection:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
