apiVersion: v1
kind: Service
metadata:
  name: sentimentanalysis-service
spec:
  selector:
    app: sentimentanalysis
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentimentanalysis
spec:
  selector:
    matchLabels:
      app: sentimentanalysis
  replicas: 2
  template:
    metadata:
      labels:
        app: sentimentanalysis
    spec:
      containers:
      - name: sentimentanalysis
        image: sentimentanalysis:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
